USE [master]
GO
/****** Object:  Database [bws]    Script Date: 5/19/2019 9:37:53 AM ******/
CREATE DATABASE [bws]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bws', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\bws.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'bws_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\bws_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [bws] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bws].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [bws] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [bws] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [bws] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [bws] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [bws] SET ARITHABORT OFF 
GO
ALTER DATABASE [bws] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [bws] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [bws] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [bws] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [bws] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [bws] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [bws] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [bws] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [bws] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [bws] SET  DISABLE_BROKER 
GO
ALTER DATABASE [bws] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [bws] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [bws] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [bws] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [bws] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [bws] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [bws] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [bws] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [bws] SET  MULTI_USER 
GO
ALTER DATABASE [bws] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [bws] SET DB_CHAINING OFF 
GO
ALTER DATABASE [bws] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [bws] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [bws] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [bws] SET QUERY_STORE = OFF
GO
USE [bws]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [bws]
GO
/****** Object:  Table [dbo].[Clients]    Script Date: 5/19/2019 9:37:53 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clients](
	[ClientID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[UserID] [numeric](18, 0) NULL,
	[ClientUserName] [nvarchar](50) NULL,
	[ClientPassword] [nvarchar](50) NULL,
	[ClientFullName] [nvarchar](50) NULL,
	[ClientMobile] [nvarchar](50) NULL,
	[ClientEmail] [nvarchar](150) NULL,
	[ClientCounty] [nvarchar](50) NULL,
	[ClientStatus] [int] NULL,
	[ClientCreatedDate] [datetime] NULL,
	[ClientUseFilter] [int] NULL,
	[ClientUseGrabber] [int] NULL,
	[ClientUserGroupPoster] [int] NULL,
	[ClientUseMultiAccount] [int] NULL,
	[ClientTurboMode] [int] NULL,
	[ClientDemo] [int] NULL,
	[ClientExpiryDate] [datetime] NULL,
 CONSTRAINT [PK_Clients] PRIMARY KEY CLUSTERED 
(
	[ClientID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 5/19/2019 9:37:54 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UserID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[UserName] [nvarchar](50) NULL,
	[Password] [nvarchar](50) NULL,
	[Fullname] [nvarchar](50) NULL,
	[Email] [nvarchar](150) NULL,
	[Mobile] [nvarchar](50) NULL,
	[Country] [nvarchar](50) NULL,
	[CreatedDate] [datetime] NULL,
	[Status] [int] NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Clients] ADD  CONSTRAINT [DF_Clients_ClientUserName]  DEFAULT ('') FOR [ClientUserName]
GO
ALTER TABLE [dbo].[Clients] ADD  CONSTRAINT [DF_Clients_ClientPassword]  DEFAULT ('') FOR [ClientPassword]
GO
ALTER TABLE [dbo].[Clients] ADD  CONSTRAINT [DF_Clients_ClientFullName]  DEFAULT ('') FOR [ClientFullName]
GO
ALTER TABLE [dbo].[Clients] ADD  CONSTRAINT [DF_Clients_ClientMobile]  DEFAULT ('') FOR [ClientMobile]
GO
ALTER TABLE [dbo].[Clients] ADD  CONSTRAINT [DF_Clients_ClientEmail]  DEFAULT ('') FOR [ClientEmail]
GO
ALTER TABLE [dbo].[Clients] ADD  CONSTRAINT [DF_Clients_ClientCounty]  DEFAULT ('') FOR [ClientCounty]
GO
ALTER TABLE [dbo].[Clients] ADD  CONSTRAINT [DF_Clients_ClientStatus]  DEFAULT ((0)) FOR [ClientStatus]
GO
ALTER TABLE [dbo].[Clients] ADD  CONSTRAINT [DF_Clients_ClientCreatedDate]  DEFAULT (getdate()) FOR [ClientCreatedDate]
GO
ALTER TABLE [dbo].[Clients] ADD  CONSTRAINT [DF_Clients_ClientUseFilter]  DEFAULT ((0)) FOR [ClientUseFilter]
GO
ALTER TABLE [dbo].[Clients] ADD  CONSTRAINT [DF_Clients_ClientUseGrabber]  DEFAULT ((0)) FOR [ClientUseGrabber]
GO
ALTER TABLE [dbo].[Clients] ADD  CONSTRAINT [DF_Clients_ClientUserGroupPoster]  DEFAULT ((0)) FOR [ClientUserGroupPoster]
GO
ALTER TABLE [dbo].[Clients] ADD  CONSTRAINT [DF_Clients_ClientUseMultiAccount]  DEFAULT ((0)) FOR [ClientUseMultiAccount]
GO
ALTER TABLE [dbo].[Clients] ADD  CONSTRAINT [DF_Clients_ClientTurboMode]  DEFAULT ((0)) FOR [ClientTurboMode]
GO
ALTER TABLE [dbo].[Clients] ADD  CONSTRAINT [DF_Clients_ClientDemo]  DEFAULT ((0)) FOR [ClientDemo]
GO
USE [master]
GO
ALTER DATABASE [bws] SET  READ_WRITE 
GO
